version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - bodyclose
    - noctx
    - misspell
    - whitespace
    - godot
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          arguments:
            - disableStutteringCheck
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    godot:
      scope: declarations
      capital: true
  exclusions:
    paths:
      - docs
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
      - path: _test\.go
        text: "should have comment"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/warenikov/gofermart

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
