// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/warenikov/gofermart/internal/accrual"
)

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) GetOrder(ctx context.Context, number string) (*accrual.OrderInfo, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *accrual.OrderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*accrual.OrderInfo, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *accrual.OrderInfo); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrual.OrderInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockAccrualClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockAccrualClient_Expecter) GetOrder(ctx interface{}, number interface{}) *MockAccrualClient_GetOrder_Call {
	return &MockAccrualClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, number)}
}

func (_c *MockAccrualClient_GetOrder_Call) Run(run func(ctx context.Context, number string)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) Return(orderInfo *accrual.OrderInfo, err error) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(orderInfo, err)
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) RunAndReturn(run func(ctx context.Context, number string) (*accrual.OrderInfo, error)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
